#include "light_rocr/transport/hsakmt/status.hpp"

#include <hsakmt/hsakmt.h>

namespace light_rocr::transport::hsakmt {

const char *hsakmt_status_name(uint32_t status) {
  switch (static_cast<HSAKMT_STATUS>(status)) {
  case HSAKMT_STATUS_SUCCESS:
    return "HSAKMT_STATUS_SUCCESS";
  case HSAKMT_STATUS_ERROR:
    return "HSAKMT_STATUS_ERROR";
  case HSAKMT_STATUS_DRIVER_MISMATCH:
    return "HSAKMT_STATUS_DRIVER_MISMATCH";
  case HSAKMT_STATUS_INVALID_PARAMETER:
    return "HSAKMT_STATUS_INVALID_PARAMETER";
  case HSAKMT_STATUS_INVALID_HANDLE:
    return "HSAKMT_STATUS_INVALID_HANDLE";
  case HSAKMT_STATUS_INVALID_NODE_UNIT:
    return "HSAKMT_STATUS_INVALID_NODE_UNIT";
  case HSAKMT_STATUS_NO_MEMORY:
    return "HSAKMT_STATUS_NO_MEMORY";
  case HSAKMT_STATUS_BUFFER_TOO_SMALL:
    return "HSAKMT_STATUS_BUFFER_TOO_SMALL";
  case HSAKMT_STATUS_NOT_IMPLEMENTED:
    return "HSAKMT_STATUS_NOT_IMPLEMENTED";
  case HSAKMT_STATUS_NOT_SUPPORTED:
    return "HSAKMT_STATUS_NOT_SUPPORTED";
  case HSAKMT_STATUS_UNAVAILABLE:
    return "HSAKMT_STATUS_UNAVAILABLE";
  case HSAKMT_STATUS_OUT_OF_RESOURCES:
    return "HSAKMT_STATUS_OUT_OF_RESOURCES";
  case HSAKMT_STATUS_KERNEL_IO_CHANNEL_NOT_OPENED:
    return "HSAKMT_STATUS_KERNEL_IO_CHANNEL_NOT_OPENED";
  case HSAKMT_STATUS_KERNEL_COMMUNICATION_ERROR:
    return "HSAKMT_STATUS_KERNEL_COMMUNICATION_ERROR";
  case HSAKMT_STATUS_KERNEL_ALREADY_OPENED:
    return "HSAKMT_STATUS_KERNEL_ALREADY_OPENED";
  case HSAKMT_STATUS_HSAMMU_UNAVAILABLE:
    return "HSAKMT_STATUS_HSAMMU_UNAVAILABLE";
  case HSAKMT_STATUS_WAIT_FAILURE:
    return "HSAKMT_STATUS_WAIT_FAILURE";
  case HSAKMT_STATUS_WAIT_TIMEOUT:
    return "HSAKMT_STATUS_WAIT_TIMEOUT";
  case HSAKMT_STATUS_MEMORY_ALREADY_REGISTERED:
    return "HSAKMT_STATUS_MEMORY_ALREADY_REGISTERED";
  case HSAKMT_STATUS_MEMORY_NOT_REGISTERED:
    return "HSAKMT_STATUS_MEMORY_NOT_REGISTERED";
  case HSAKMT_STATUS_MEMORY_ALIGNMENT:
    return "HSAKMT_STATUS_MEMORY_ALIGNMENT";
  }
  return "HSAKMT_STATUS_UNKNOWN";
}

} // namespace light_rocr::transport::hsakmt
