#ifndef LIGHT_ROCR_TOOLS_FIXED_GFX1101_STORE_HPP
#define LIGHT_ROCR_TOOLS_FIXED_GFX1101_STORE_HPP

#include <array>
#include <cstddef>
#include <cstdint>
#include <cstring>
#include <type_traits>

namespace light_rocr::tools::fixed_gfx1101_store {

inline constexpr uint64_t kCodeOffset = 256;
inline constexpr uint32_t kExpectedValue = 0x51a7c0de;

// AMDHSA code-object-v6 kernel descriptor generated by the assembler source
// beside this header. The entry offset is adjusted for the fixed in-memory
// image below, so no ELF loading or relocation is involved in this smoke test.
struct alignas(64) KernelDescriptor {
  uint32_t group_segment_fixed_size = 0;
  uint32_t private_segment_fixed_size = 0;
  uint32_t kernarg_size = 16;
  uint8_t reserved0[4] = {};
  int64_t kernel_code_entry_byte_offset = static_cast<int64_t>(kCodeOffset);
  uint8_t reserved1[20] = {};
  uint32_t compute_pgm_rsrc3 = 0;
  uint32_t compute_pgm_rsrc1 = 0x60af0000;
  uint32_t compute_pgm_rsrc2 = 0x00000004;
  uint16_t kernel_code_properties = 0x0408;
  uint16_t kernarg_preload = 0;
  uint8_t reserved3[4] = {};
};

static_assert(std::is_standard_layout_v<KernelDescriptor>);
static_assert(sizeof(KernelDescriptor) == 64);
static_assert(alignof(KernelDescriptor) == 64);
static_assert(offsetof(KernelDescriptor, kernel_code_entry_byte_offset) == 16);
static_assert(offsetof(KernelDescriptor, compute_pgm_rsrc3) == 44);
static_assert(offsetof(KernelDescriptor, compute_pgm_rsrc1) == 48);
static_assert(offsetof(KernelDescriptor, compute_pgm_rsrc2) == 52);
static_assert(offsetof(KernelDescriptor, kernel_code_properties) == 56);

struct alignas(16) Kernarg {
  uint64_t output_address = 0;
  uint32_t value = 0;
  uint32_t reserved = 0;
};

static_assert(sizeof(Kernarg) == 16);
static_assert(alignof(Kernarg) == 16);

// Exact gfx1101 encoding of fixed_gfx1101_store.s. It loads an output GPU VA
// and a 32-bit value from kernarg, performs one global store, waits for the
// store, and terminates. Keeping this fixed image independent of the Loader is
// intentional: the first dispatch isolates queue/packet/doorbell/signal bugs.
inline constexpr std::array<uint32_t, 12> kCode = {
    0xf4040080, 0xf8000000, // s_load_b64 s[2:3], s[0:1], 0x0
    0xf4000000, 0xf8000008, // s_load_b32 s0, s[0:1], 0x8
    0xbf89fc07,             // s_waitcnt lgkmcnt(0)
    0x7e000202,             // v_mov_b32_e32 v0, s2
    0x7e020203,             // v_mov_b32_e32 v1, s3
    0x7e040200,             // v_mov_b32_e32 v2, s0
    0xdc6a0000, 0x007c0200, // global_store_b32 v[0:1], v2, off
    0xbf8903f7,             // s_waitcnt vmcnt(0)
    0xbfb00000,             // s_endpgm
};

static_assert(__BYTE_ORDER__ == __ORDER_LITTLE_ENDIAN__,
              "fixed gfx1101 instruction words require a little-endian host");
static_assert(kCodeOffset + sizeof(kCode) <= 4096);

inline bool write_image(void *allocation, size_t allocation_size) {
  if (allocation == nullptr ||
      reinterpret_cast<uintptr_t>(allocation) % alignof(KernelDescriptor) !=
          0 ||
      allocation_size < kCodeOffset + sizeof(kCode)) {
    return false;
  }
  std::memset(allocation, 0, allocation_size);
  const KernelDescriptor descriptor;
  std::memcpy(allocation, &descriptor, sizeof(descriptor));
  auto *bytes = static_cast<uint8_t *>(allocation);
  std::memcpy(bytes + kCodeOffset, kCode.data(), sizeof(kCode));
  return true;
}

} // namespace light_rocr::tools::fixed_gfx1101_store

#endif
